title: NezzBlog
description:
author: Ivan Wu
avatar: /logo.jpg
email: ivan055111@gmail.com
skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
google_analytics: UA-81712264-2

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Ivan Wu
  links:
    - https://github.com/ivanisidrowu
google_site_verification: 
lang: en
